-- Wid Wins Supabase schema
-- Run this in the Supabase SQL editor once before deploying the Vercel app.

create extension if not exists pgcrypto;

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  message text,
  stage text,
  email text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.idea_intakes (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  full_name text,
  email text,
  phone text,
  idea_summary text,
  problem text,
  target_users text,
  primary_goal text,
  current_stage text,
  budget text,
  timeline text,
  refined_summary text,
  conversation_summary text,
  qa_history jsonb not null default '[]'::jsonb,
  latest_question text,
  latest_answer text,
  status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lead_captures (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  full_name text,
  email text,
  phone text,
  lead_type text,
  recommended_package text,
  idea_summary text,
  problem text,
  target_users text,
  primary_goal text,
  current_stage text,
  budget text,
  timeline text,
  commitment_level text,
  conversation_summary text,
  notes text
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_idea_intakes_updated_at on public.idea_intakes;
create trigger trg_idea_intakes_updated_at
before update on public.idea_intakes
for each row execute function public.set_updated_at();
